name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: devitcf/money-tab_telegram-bot
          secrets: |
              "github_token=${{ secrets.GITHUB_TOKEN }}"  


